version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db/dbname
      - PYTHONPATH=/code
      - POOL_SIZE=250
      - MAX_OVERFLOW=50
      - POOL_TIMEOUT=30
      - POOL_RECYCLE=1800
    volumes:
      - ./app:/code/app
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/code
    volumes:
      - ./streamlit_app:/code/streamlit_app

  db:
    image: postgres:13
    command: -c 'max_connections=500' -c 'max_locks_per_transaction=128'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
