# Dockerfile.fastapi

FROM python:3.12

WORKDIR /code

# Copy the requirements file and install dependencies
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the application code
COPY ./app /code/app

# Copy the wait_for_db script
COPY ./wait_for_db.py /code/wait_for_db.py

# Copy Alembic configuration and migration scripts
COPY ./alembic.ini /code/alembic.ini
COPY ./alembic /code/alembic

# Set the PYTHONPATH
ENV PYTHONPATH=/code

# Expose the port for FastAPI
EXPOSE 8000

# Create a script to run FastAPI
RUN echo '#!/bin/sh\n\
python /code/wait_for_db.py && \
alembic upgrade head && \
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload' > /code/start_fastapi.sh && chmod +x /code/start_fastapi.sh

# Run the FastAPI start script
CMD ["/code/start_fastapi.sh"]
