version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
      - streamlit
      - prometheus

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/code
      - POOL_SIZE=250
      - MAX_OVERFLOW=50
      - POOL_TIMEOUT=30
      - POOL_RECYCLE=1800
    volumes:
      - ./app:/code/app
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini
      - ./.env:/code/.env
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    expose:
      - "8501"
    environment:
      - PYTHONPATH=/code
      - POOL_SIZE=250
      - MAX_OVERFLOW=50
      - POOL_TIMEOUT=30
      - POOL_RECYCLE=1800
    volumes:
      - ./streamlit_app:/code/streamlit_app
      - ./.env:/code/.env

  prometheus:
    image: prom/prometheus:v2.30.3
    depends_on:
      - fastapi
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.external-url=/prometheus"
      - "--web.route-prefix=/prometheus"
    expose:
      - "9090"
    restart: always

volumes:
  prometheus_data:
  grafana_data:
