global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi:8000']
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
