"""Initial migration

Revision ID: 69aa2f5efc79
Revises: 484c85b7860d
Create Date: 2024-08-17 02:57:26.288470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69aa2f5efc79'
down_revision: Union[str, None] = '484c85b7860d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_response_logs', sa.Column('event_time', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('request_response_logs', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_response_logs', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('request_response_logs', 'event_time')
    # ### end Alembic commands ###
