"""Initial migration

Revision ID: 9e4e738b969c
Revises: 0ddf686f4396
Create Date: 2024-08-17 03:22:25.567333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4e738b969c'
down_revision: Union[str, None] = '0ddf686f4396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_response_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('partition_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'partition_key'),
    postgresql_partition_by='LIST (partition_key)'
    )
    op.create_index(op.f('ix_request_response_logs_method'), 'request_response_logs', ['method'], unique=False)
    op.create_index(op.f('ix_request_response_logs_url'), 'request_response_logs', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_response_logs_url'), table_name='request_response_logs')
    op.drop_index(op.f('ix_request_response_logs_method'), table_name='request_response_logs')
    op.drop_table('request_response_logs')
    # ### end Alembic commands ###
