"""Migration to Async Postgres

Revision ID: dcadfc57bf92
Revises: 3e3fa4698500
Create Date: 2024-08-19 17:00:20.194541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcadfc57bf92'
down_revision: Union[str, None] = '3e3fa4698500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
